### PR TITLE
Persist time display choice and add "hide time" intent

### PR DESCRIPTION
**Pull request by skeledrew**
My first Mycroft PR! This PR persists the time display state to settings.json, so it is preserved across reloads. Also added the ability to *hide time* and highlighted the presence of *show time* in the readme.

### CODE REVIEW

**Comment by Mn0491** [comment]
@skeledrew, I see that you interfaced with the settings.json by creating your own function that reads from settings.json. Mycroft core has that built in. https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/skills/settings.py

I think a better approach to this is using the self.settings interface. Check out the code in pianobar and how they leveraged it. https://github.com/ethanaward/pianobar-skill

**Comment by skeledrew** [comment]
@Mn0491 Thanks for the review. I switched to the self.settings method, but it doesn't seem to be working, as the settings.json file hasn't been modified since the switch. I think I saw a permissions error when it was trying to access it. Also I had to manually define self._dir, so there seems to be a missing mechanism to get the path. I'll continue looking into it.

**Comment by Mn0491** [comment]
@skeledrew are you on the mark 1 or picroft platform? If you are, make sure the skill files have permissions for the Mycroft user.

**Comment by skeledrew** [comment]
@Mn0491 I am using the Mark 1 for dev, and msm to install skills, so they all have the right perms. The only difference I've made to a couple skills is make them writeable by "other".

**Comment by penrods** [comment]
I'm looking at this.  I think the issue is with the initialization of self._dir and the utilization of self.settings. 
 You should not be setting that property (although I see why you tried to).  The the way things function at the moment, the self._dir does not get set by the framework until AFTER the object constructor has completely executed.  So accessing self.settings in the __init__() will not work, you would have to wait until the framework calls the initialize() method instead.

However, I believe the code you use, @skeledrew, is very logical and will be a commonly attempted approach.  Let me see if we can adjust the initialization to allow your code to work (minus you setting self._dir).  I'll get back with you.

**Comment by forslund** [comment]
The `_dir` isn't available until initialize()

**Comment by penrods** [comment]
We are pulling in a few changes to make what you've done work (minus setting self._dir yourself).  Let's hold off until 0.8.22 in a few days to get this updated and merged.

**Comment by skeledrew** [comment]
@penrods I would think since _settings is initialized in the super call then it would get all it needs at that point to be functional. There really needs to be a list of tips, best practices, etc stating for ex what can go into __init__ to avoid situations like this. I was honestly starting to get frustrated over having to change something that was already working and spend 3x more time doing it the "preferred" way. I think I finally have it now though.

**Comment by skeledrew** [comment]
Also I wasn't sure if persists should happen when the time is merely spoken and on stop(), so I merely commented the relevant lines.

**Comment by MatthewScholefield** [comment]
@skeledrew Thanks for the feedback, we do really need clearer documentation on what tools a skill has to use. While not comprehensive, we recently (a few hours ago) published docs that may help [right here][docs], but we still have to append to that information about data members like `self.enclosure`.
[docs]:http://mycroft-core.readthedocs.io/en/latest/source/mycroft.html#mycroft.MycroftSkill

**Comment by penrods** [comment]
This is superseded by #19.  Closing.

**Pull request closed without merging**
