### PR TITLE
Add Skill API decorators and docstrings

### PR DESCRIPTION
**Pull request by krisgesling**
#### Description
Add Skill API decorators and docstrings to methods used by the Homescreen Skill.

This enables the Homescreen Skill, and any others, to utilize the Date Time Skills methods in a structured way.

#### Type of PR
- [ ] Bugfix
- [x] Feature implementation
- [ ] Refactor of code (without functional changes)
- [ ] Documentation improvements
- [ ] Test improvements

#### Testing
Requires another PR in Homescreen Skill

#### Documentation
Docstrings updated

### CODE REVIEW

**Review by chrisveilleux — APPROVED** [review]
always love more documentation.  nice work.

**Comment by krisgesling** [comment]
Just had a thought - is there any chance these methods will change in the near future? ie are you doing a "Make Datetime Great Again" refactor?

If so it might be worth holding this off so we don't expose a public API for the Skill and then immediately change it.

**Comment by chrisveilleux** [comment]
Yes, I do plan on a major refactor of this code.  Let's sit on this for now.

**Comment by krisgesling** [comment]
Closing in favour of the new Time Skill and Date Skill.

**Pull request closed without merging**
