### PR TITLE
Add danish

### PR DESCRIPTION
**Pull request by andlo**

### CODE REVIEW

**Comment by forslund** [comment]
Thanks @andlo. Looks pretty good, can you remove the commented out english lines?

I'd prefer if this was contributed through the translate.mycroft.ai since we only have a one way pipeline at the moment this may get overwritten when the date-time translation i completed there.

**Comment by andlo** [comment]
I thaught that the comments were legal....That makes it easy to figure out what the meaning is.....
If it conflicts with translate and there isnt any way to merge whith that you can close this PR.
I just cant translate and work with translations when waiting on pootle get merged. And then when something dosnt sound right find the problem localy, fix it and then find the same on pootle.....speciel if not having the English comment to use when searching for a bad translation on pootle. 
When using mycroft, and he says something funny - it is easy to trace down where and correct that localy. And then it is harder to find the same problem on pootle and correct it there to.

**Comment by forslund** [comment]
The comments are legal, they just makes the sanity check (I still do) when merging pootle translations harder.

**Comment by andlo** [comment]
Åhhh that is nt good. We dont like work to be harder than nessasary ;) 
Then skip this PR, and just use the stuff on poodle. Then I just use translations localy until they come from poodle :)

**Comment by forslund** [comment]
I'd much rather include your contributions, if this is the way you want to deliver them that's fine. You're offering up your free time to make a better experience for everyone so I don't mean to be negative.

**Comment by andlo** [comment]
I am sertently not se you or anyone negative :) I use my freetime as I want for sure, and dooing mycroft is wat I want mostly because it is fun but sertenly also because the people in and around mycroft are nice and helpfull and I feel like a part of that. And that is a goood feeling :) And I lear something new everyday.
For me it is easer to have comments in the voc, regex and dialogfiles but if it is interfeering pootle integration I will remove them.
But maybe you could just add a preprocessing part that removes all comment lines ?

**Pull request closed without merging**
