### PR TITLE
Add more German phrases

### PR DESCRIPTION
**Pull request by flozi00**

### CODE REVIEW

**Comment by flozi00** [comment]
@krisgesling

**Comment by krisgesling** [comment]
Hi Flozi, sorry for the slow response.

These types of translations are best entered in Translate.mycroft.ai as our scripts will overwrite content that isn't consistent with data being exported from translate.

The what-time-will-it-be change should be easily included in our translation platform. You can always add extra variations to a phrase by using the options syntax eg `(this|that)`. So rather than having two lines:
```
wie ist die Zeit in {location} in {offset} (Stunden | Minuten | Sekunden) (von jetzt!)
Was ist die Zeit in {location} in {offset} (Stunden | Minuten | Sekunden) (ab jetzt | von jetzt)
```
Is the following acceptable?
```
(was|wie) ist die Zeit in {location} in {offset} (Stunden | Minuten | Sekunden) (ab jetzt | von jetzt)
```
It's a little harder with the other intent. In the English form these are caught using keywords eg "what" + "time".
So I'm wondering if we should add "wie" and "wast" to [`Query.voc`](https://translate.mycroft.ai/projects/mycroft-skills/translate/skill-date-time-de.po#search=tags%2Fskill-date-time%2FQuery.voc%3A1&sfields=locations). Would they translate as "what"?
"spät" could be added to [`time.voc`](https://translate.mycroft.ai/projects/mycroft-skills/translate/skill-date-time-de.po#search=tags%2Fskill-date-time%2FTime.voc%3A1&sfields=locations)

**Comment by flozi00** [comment]
okay, so I need to add more phrases in english files ?

**Comment by krisgesling** [comment]
Ideally we can just add these into the Translate platform. 

The input field for translations allows for multi-line inputs though I'm not confident on how our scripts will handle that. It may just work as really they're just carriage return characters in the end... but I'd like to test this before trying it in production.

**Pull request closed without merging**
